Jar with lombok
MV-shallow/NumberStats pull request #3
Opened 2021-06-16 13:46 UTC by MV-shallow

2021-06-16 13:51 UTC, MV-shallow commented
![image](https://user-images.githubusercontent.com/62831519/122231448-cc9fbb00-cefd-11eb-9c86-b27ea5580b91.png)

2021-06-16 13:52 UTC, MV-shallow commented
![image](https://user-images.githubusercontent.com/62831519/122231601-e6410280-cefd-11eb-8e3b-93c7d154448b.png)

2021-06-21 03:25 UTC, progressicu requested changes

2021-06-21 03:25 UTC, progressicu commented on src/test/java/org/WhiteSoftStudent/utility/output/impl/FileOutputTest.java
> +        fileOutput = new FileOutput();
Необязательно в setUp создавать тестируемый класс. Можно было просто как поле

2021-06-21 03:25 UTC, progressicu commented on src/main/java/org/WhiteSoftStudent/utility/output/impl/FileOutput.java
> +    File outputFile;
Бины не должны хранить состояние. Т.е. в твоем случае, если тебе нужен был outputFile, то ты его в методе и создаешь

2021-06-21 03:25 UTC, progressicu commented on src/test/java/org/WhiteSoftStudent/utility/output/impl/FileOutputTest.java
> +        fileOutput.filename = "./../output_test.txt";
Если нужно задать бину переменную, то воспользуйся конструктором или setter-ом по крайней мере, в котором будет проверка, что пришел действительно путь, а не что-дибо еще или null

2021-06-21 03:25 UTC, progressicu commented on src/test/java/org/WhiteSoftStudent/utility/output/impl/FileOutputTest.java
> +    void presentData() {
Сделай тесты через Arrange, Act, Assert (загугли, если не рассказывали)

2021-06-21 03:25 UTC, progressicu commented on src/main/java/org/WhiteSoftStudent/outputManager/OutputManager.java
> +@Getter
Вместо getter-а, можно было написать метод в классе getExisting(String), который найдет в map данное значение, а если нет, то кинет исключение

2021-06-21 03:25 UTC, progressicu commented on src/main/java/org/WhiteSoftStudent/calculator/Calculator.java
> +@Component
Так и не понял для чего тебе этот бин. Если где нужен был List<Calculation>, то можно было сразу туда их положить. Зачем усложнять

2021-06-21 03:25 UTC, progressicu commented on src/main/java/org/WhiteSoftStudent/calculation/impl/AvgDigit.java
> +        return String.format("Avg digit is %.2f", digit);
А если придет сюда не число? Неправильно принимать Object в данном случае, придумай что-нибудь по лучше

2021-06-21 03:25 UTC, progressicu commented on src/main/java/org/WhiteSoftStudent/utility/Input.java
>  public class Input {
Если это у тебя утилитный класс (что вроде как и есть), то назови его соответствующе.
И методы должны быть с маленькой буквы

2021-06-21 03:25 UTC, progressicu commented on src/main/java/org/WhiteSoftStudent/utility/output/impl/ConsoleOutput.java
> +@Component("console")
Это лишне указывать наименование бина

2021-06-21 03:25 UTC, progressicu commented on src/main/java/org/WhiteSoftStudent/calculation/Calculation.java
> +    Object CalculateValue(int[] array);
Почему это возвращает Object, а ниже принимает? Возможно подойдет Number, а может лучше во всех случаях возвращать double, и потом только в одном месте приводить это. Проработай это

2021-06-21 03:25 UTC, progressicu commented on src/main/java/org/WhiteSoftStudent/utility/output/impl/FileOutput.java
> +                System.out.println("[Rewriting]");
Здесь, ниже и в других случаях мы не пишем в консоль. Т.к. ты подключил spring-boot, то у тебя автоматом появились зависимости на библиотеки логгирования и с помощью аннотации `@Slf4j` от lombok тебе добавится сразу нужный объект, вот с помощью него и пиши в лог.

В консоль можно писать в исключительных случаях, например, как в классе ConsoleOutput, там это сойдет, но тут и ниже при exception нет

2021-06-22 00:10 UTC, progressicu requested changes

2021-06-22 00:10 UTC, progressicu commented on src/main/java/org/theWhite/utility/output/impl/FileOutput.java
> +                new PrintWriter(filename).close();
А для чего данная сомнительная конструкция?

2021-06-22 00:10 UTC, progressicu commented on src/main/java/org/theWhite/utility/output/impl/FileOutput.java
> +    Formatter formatter;
Всё равно у тебя получается, что бин хранит состояние. Чтобы этого избежать можно было в createOrClearFile() вернуть formatter и потом в presentData сразу его заиспользовать (только метод createOrClearFile переименуй тогда, т.к. не совсем подходящее описание будет)
А если Formatter поддерживает AutoCloaseable (посмотри, что это), то еще лучше будет

2021-06-22 00:10 UTC, progressicu commented on src/main/java/org/theWhite/utility/output/impl/FileOutput.java
> +    String getFilename() {
А можно было просто @Getter с соответствующим accessLevel

2021-06-22 00:10 UTC, progressicu commented on src/test/java/org/theWhite/utility/output/impl/FileOutputTest.java
>          } catch (IOException e) {
В тестах стараемся не использовать try-catch, а просто кидаем исключения выше

2021-06-22 00:26 UTC, progressicu commented on src/main/java/org/theWhite/runner/ConsoleRunner.java
>              System.out.print("Output type: ");
Здесь наверное стоит вывести возможные ответы пользователю

2021-06-22 04:20 UTC, MV-shallow commented on src/main/java/org/theWhite/App.java
> +package org.theWhite;
Перепутал с CamelCase...

2021-06-22 06:00 UTC, progressicu approved these changes

2021-06-22 06:06 UTC, progressicu commented
> ![image](https://user-images.githubusercontent.com/62831519/122231601-e6410280-cefd-11eb-8e3b-93c7d154448b.png)

Обнови вывод. Посмотрим, как сейчас это всё будет

2021-06-22 16:05 UTC, MV-shallow commented on src/main/java/org/thewhite/utility/output/impl/FileOutput.java
> +                    throw new IllegalArgumentException();
![image](https://user-images.githubusercontent.com/62831519/122961120-70d6a580-d3c7-11eb-8bce-618fce90ccd6.png)
Теперь так.

2021-06-22 16:08 UTC, MV-shallow commented on src/main/java/org/thewhite/utility/output/impl/FileOutput.java
> +                    throw new IllegalArgumentException();
![image](https://user-images.githubusercontent.com/62831519/122961577-dc207780-d3c7-11eb-8d5d-8cc0e2da39d3.png)

2021-06-22 16:11 UTC, MV-shallow commented
![image](https://user-images.githubusercontent.com/62831519/122961922-3ae5f100-d3c8-11eb-846f-8321736d3b8b.png)
![image](https://user-images.githubusercontent.com/62831519/122961969-489b7680-d3c8-11eb-8a63-b75a82cfd316.png)

2021-06-23 01:34 UTC, MV-shallow commented on src/main/java/org/thewhite/utility/output/impl/FileOutput.java
> +                    throw new IllegalArgumentException();
Еще такой вариант (я пока что свободен, поэтому переделал)
![image](https://user-images.githubusercontent.com/62831519/123021123-d43bf400-d416-11eb-9df0-96e302a87466.png)
![image](https://user-images.githubusercontent.com/62831519/123021171-eb7ae180-d416-11eb-872d-82c84a47336e.png)

2021-06-23 09:14 UTC, merged