REST
MV-shallow/NumberStats pull request #4
Opened 2021-07-03 14:05 UTC by MV-shallow

![image](https://user-images.githubusercontent.com/62831519/124356808-7e0f5200-dc5b-11eb-8fbc-887663905489.png)
![image](https://user-images.githubusercontent.com/62831519/124356821-8d8e9b00-dc5b-11eb-9c7a-a10e68e6f61e.png)

2021-07-03 14:06 UTC, MV-shallow commented
Использовал springdoc вместо springfox, т.к. там было легче UI настроить.

2021-07-03 14:08 UTC, MV-shallow commented
Еще есть недочет с аннотацией RequestBody, если использовать от спринга, то все нормально, но она слишком ограничена. Если брать от oas3, можно пример тела запроса в коде прописать, но при этом в запросе с отсутствующим телом контроллер будет получать null. Из-за этого срабатывает другое исключение(оно тоже проверяется, но это уже не отсутствие тела запроса).

2021-07-04 07:30 UTC, progressicu requested changes

2021-07-04 07:30 UTC, progressicu commented on src/main/java/org/thewhite/rest/controller/Controller.java
> +@RequestMapping(value = "math/calculate", method = RequestMethod.POST)
А для чего метод указываешь?

2021-07-04 07:30 UTC, progressicu commented on pom.xml
> +            <artifactId>springdoc-openapi-ui</artifactId>
Так и не понял, чем сложнее сконфигурировать springfox и чем это лучше. springfox даёт больше возможностей (увидел что по крайней мере, как раз, например, в создание примера дто. Просто нужно разобраться

2021-07-04 07:30 UTC, progressicu commented on src/main/java/org/thewhite/rest/controller/Controller.java
> +public class Controller {
Может как-то более информативно назвать

2021-07-04 07:30 UTC, progressicu commented on src/test/java/org/thewhite/rest/controller/ControllerIT.java
> +        mockMvc.perform(MockMvcRequestBuilders
Нужно было сделать запрос, проверить статус и вернуть в переменную String result ответ. И потом в отдельном блоке //Assert создать String expected и проверить что одинаково. Просто так не сильно удобно читать

2021-07-04 07:30 UTC, progressicu commented on src/test/java/org/thewhite/rest/controller/ControllerIT.java
> +        String responseExpectedJson = "{\n\"message\": \"No such request, check API documentation\"\n}";
Почему бы не преобразовать ответ в объект ErrorDto через objectMapper и проверить уже по полям

2021-07-04 07:30 UTC, progressicu commented on src/test/java/org/thewhite/rest/validation/dto/impl/DtoFieldsNotNullCheckTest.java
> +        DtoFieldsNotNullCheck validator = new DtoFieldsNotNullCheck();
Зачем ты каждый раз создаешь проверяемый объект. Возьми и вынеси его в поле тестового класса и в методах просто используй

2021-07-04 07:30 UTC, progressicu commented on src/test/java/org/thewhite/rest/validation/number/impl/IsValidNumberCheckTest.java
> +        checker = new IsValidNumberCheck();
И зачем в BeforeEach? Почему сразу не создать при объявлении, так же проще будет код

2021-07-04 07:30 UTC, progressicu commented on src/main/java/org/thewhite/rest/service/CalculationService.java
> +        List<String> descriptions = new Vector<>();
Vector очень давно устаревший класс

2021-07-04 07:30 UTC, progressicu commented on src/test/resources/application.properties
> +validation.dto.dto-fields-not-null-check=true
для чего дублировать одно и тоже слово в пределах одной проперти? Не очень выглядит

2021-07-04 11:12 UTC, MV-shallow commented on src/main/java/org/thewhite/rest/RestApiExceptionHandler.java
> +@EnableWebMvc
Да, иначе не будет кидаться NoHandlerFoundException

2021-07-04 11:13 UTC, MV-shallow commented on src/main/java/org/thewhite/rest/service/CalculationService.java
> +        List<String> descriptions = new Vector<>();
И чем это плохо? Что лучше использовать?

2021-07-04 11:17 UTC, MV-shallow commented on src/main/java/org/thewhite/rest/RestApiExceptionHandler.java
> +    public ResponseEntity<Object> handleNoParameterValueException(RuntimeException ex) {
Как в таком случае возвращать код ответа? Через поле в dto? Как-то неестественно и костыльно будет. Взял ResponseEntity, потому что на Baeldung его возвращали в примере и Влад так же сделал.

2021-07-04 11:24 UTC, MV-shallow commented on src/main/java/org/thewhite/rest/RestApiExceptionHandler.java
> +    public ResponseEntity<Object> handleNoParameterValueException(RuntimeException ex) {
Хм, в твоем примере через аннотацию. Но есть ли разница? Могу переделать.

2021-07-04 11:47 UTC, MV-shallow commented on pom.xml
> +            <artifactId>springdoc-openapi-ui</artifactId>
![image](https://user-images.githubusercontent.com/62831519/124383734-6692a080-dd11-11eb-9d46-2df211613c13.png)
C примером уже разобрался.  Хватило одной аннотации для поля:  @Schema(example = "12345")

2021-07-04 12:42 UTC, progressicu requested changes

2021-07-04 12:42 UTC, progressicu commented on src/main/java/org/thewhite/rest/RestApiExceptionHandler.java
> +    public ResponseEntity<Object> handleNoParameterValueException(RuntimeException ex) {
ResponseEntity в данном случае лишний код, т.к. по факту работает как обертка с функцией проставления статуса. Но для этого есть аннотации. По ним сразу просто видно, что в случае с такой-то ошибкой, будет такой статус. А иногда обработка сложная. Да и просто без ResponseEntity код становится похож на контроллер, что позволяет его легче воспринимать

2021-07-04 12:42 UTC, progressicu commented on src/main/java/org/thewhite/rest/service/CalculationService.java
> +        List<String> descriptions = new Vector<>();
А ты как думаешь чем вреден старый код? В новых классах есть оптимизации, он лучше выглядит, да и другие плюсы. 
ArrayList - стандарт по факту.

2021-07-04 12:42 UTC, progressicu commented on src/main/java/org/thewhite/rest/RestApiExceptionHandler.java
> +@EnableWebMvc
Ну по факту starter-web должен вместо тебя эту аннотацию подключать. Может в новых версиях, что поменялось. Позже посмотрю, отпишусь

2021-07-04 12:42 UTC, progressicu commented on pom.xml
> +            <artifactId>springdoc-openapi-ui</artifactId>
Всё равно тоже самое, что и springfox, просто названия разные. Вот, например, [миграция](https://springdoc.org/migrating-from-springfox.html) даже написана. 

Это не плохо, что ты так сделал, т.к. разные вещи можно по разному сделать, т.е. единственно правильного решения нет. Не придираюсь, всё ок. 

Просто если собирешься к нам в компанию, то скорее всего будешь использовать springfox, т.к. он у нас пока везде. Ну а чтобы с него перейти на springdoc, то нужны весомые аргументы, т.к. тогда придется привыкать к новой библиотеке - это хоть и не сложно, но причины должны быть для чего это нужно нам делать.
Это просто так на всякий оставлю здесь

2021-07-04 12:42 UTC, progressicu commented on src/main/java/org/thewhite/rest/controller/CalculationController.java
> +                                  @RequestParam(value = "number") String number) {
value - по дефолту = названию параметра. Так что в данном случае это лишне указывать

2021-07-04 12:42 UTC, progressicu commented on src/test/java/org/thewhite/rest/controller/CalculationControllerIT.java
> +        mvcResult = mockMvc.perform(MockMvcRequestBuilders
А вот MvcResult mvcResult не нужно было выносить в поле. Т.к., например, если запустим тесты паралельно, то это всё может сломаться.

Т.е. выносим в поля только то, что остается не изменным на протяжении всех тестов

2021-07-04 12:42 UTC, progressicu commented on src/test/java/org/thewhite/rest/controller/CalculationControllerIT.java
> +                           .andReturn();
Ниже можно было строку отступить, чтобы не сливалось всё. 
И вернуть сразу строку. Т.е. мы обычно в Act делаем запрос и сразу возвращаем преобразованное тело запроса, т.е. в данном случае result должно быть строкой, а где-то может быть дто

2021-07-04 12:42 UTC, progressicu commented on pom.xml
> +            <artifactId>jackson-databind</artifactId>
После аннотации EnableWebMvc я уже сомневаюсь, но попробуй без этой зависимости. По идее она должна подтягиваться в стартере

2021-07-04 14:30 UTC, MV-shallow commented
![image](https://user-images.githubusercontent.com/62831519/124388812-dc096b80-dd27-11eb-90bf-7634b21be49e.png)
На springfox.
Всё же, конфигурация в springdoc лаконичнее и описание для контроллера понятнее составляется. Потому что в springfox для него пришлось писать так: @Api(tags = "Calculation controller",description="Provides basic API for users to get stats of supplied number"). И description тут - устаревший атрибут, хотя замены вроде бы нет.

2021-07-04 14:31 UTC, MV-shallow commented
Семантически так лучше: @Tag(name = "Calculation controller", description = "Provides basic API for users to get stats of supplied number")

2021-07-04 14:33 UTC, MV-shallow commented
![image](https://user-images.githubusercontent.com/62831519/124388964-7e295380-dd28-11eb-83ec-706871aba80a.png)
![image](https://user-images.githubusercontent.com/62831519/124388976-8c776f80-dd28-11eb-9677-9d2c6ba00758.png)

2021-07-04 14:34 UTC, MV-shallow commented
Но он сам не без минусов, конечно(springdoc). Там, например, не выпилен пример с апи магазина

2021-07-04 14:42 UTC, MV-shallow commented on src/test/java/org/thewhite/rest/controller/CalculationControllerIT.java
> +                           .andReturn();
Не нашел способ преобразования тела ответа сразу в dto кроме objectMapper.readValue(<тут весь мок-запрос>,ErrorDto.class). Но такой код нагрузку для читателя увеличит.

2021-07-04 14:43 UTC, MV-shallow commented on src/main/java/org/thewhite/rest/RestApiExceptionHandler.java
> +    public ResponseEntity<Object> handleNoParameterValueException(RuntimeException ex) {
На аннотацию не поменять теперь. Все исключения обрабатываются в приватном методе с передачей ему кода ответа. Или можно как-то лучше сделать?

2021-07-05 04:15 UTC, progressicu commented
> ![image](https://user-images.githubusercontent.com/62831519/124388812-dc096b80-dd27-11eb-90bf-7634b21be49e.png)
> На springfox.
> Всё же, конфигурация в springdoc лаконичнее и описание для контроллера понятнее составляется. Потому что в springfox для него пришлось писать так: @Api(tags = "Calculation controller",description="Provides basic API for users to get stats of supplied number"). И description тут - устаревший атрибут, хотя замены вроде бы нет.

Тебя никто и не заставлял переходить. Там нужно разобраться, т.к. я уже тоже немного запутался, потому что обычно на методы контроллера ставили `@ApiOperation`, а ты поставил просто `@Operation`, что в принципе верно, но тут тогда нужно разобраться, какой именно ты пакет используешь: io.swagger.annotations или io.swagger.v3.oas.annotations. Желательно разобраться, что лучше, т.к. я в эту тему пока не лез, пока просто делал наподобие как делал раньше, но видимо скоро придется.

Как тебе делать - решай сам. Можешь вернуть на springdoc, можешь springfox

2021-07-05 04:18 UTC, progressicu commented on src/test/java/org/thewhite/rest/validation/number/impl/constraint/SumIsNotAnUltimateAnswerCheckTest.java
> +    private final SumIsNotAnUltimateAnswerCheck checker = new SumIsNotAnUltimateAnswerCheck(new DigitsSum());
Вот тут лучше использовать mockito. Т.е. в конструктор передать мок и в тесте просто сконфигурировать, что вернется. Тогда не нужно заморачиваться с логикой DigitsSum и проверять только логику SumIsNotAnUltimateAnswerCheck

2021-07-05 05:47 UTC, progressicu approved these changes

2021-07-05 05:47 UTC, progressicu commented on src/main/java/org/thewhite/calculation/impl/MaxDigit.java
> +        return Arrays.stream(array).max().orElse(0);
А так точно следует делать, именно возвращать 0? Просто может показаться, что 0 = max digit, т.к. ошибки же не было

2021-07-05 05:47 UTC, progressicu commented on src/test/java/org/thewhite/rest/validation/number/impl/constraint/NoNumberOfTheBeastInsideCheckTest.java
> +        checker.validate("111111111111111");
Наверное здесь лушче написать, что-то типа assertDoesNotThrow. А то кажется, что просто метод вызываем

2021-07-05 05:47 UTC, progressicu commented on src/test/resources/junit-platform.properties
> +junit.jupiter.execution.parallel.mode.default = concurrent
А зачем тебе это?

2021-07-05 05:57 UTC, MV-shallow commented on src/test/resources/junit-platform.properties
> +junit.jupiter.execution.parallel.mode.default = concurrent
Параллельно тесты прогонять
https://junit.org/junit5/docs/snapshot/user-guide/index.html#writing-tests-parallel-execution

2021-07-06 02:22 UTC, progressicu commented on src/test/java/org/thewhite/rest/validation/number/impl/constraint/NoNumberOfTheBeastInsideCheckTest.java
> +        //doesn't throw exception
Так для этого же методы проверки спец. есть

2021-07-06 02:23 UTC, progressicu approved these changes

2021-07-06 02:23 UTC, progressicu commented on src/test/java/org/thewhite/rest/controller/CalculationControllerUT.java
> +class CalculationControllerUT {
UT? Кнопку перепутал походу

2021-07-06 14:01 UTC, vladislav-shelengovskiy approved these changes

2021-07-06 23:12 UTC, merged